version: '3.9'

services:
  api:
    build:
      context: ./Api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    command: ["python", "app.py"]

  client:
    build:
      context: ./Client
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host"]
